### ISSUE TITLE
"The scm url cannot be null" error with Git

### ISSUE THREAD

**Issue by hrzafer** [mojohaus/buildnumber-maven-plugin#131]
I am having this error with the following configuration.  Does  this plugin support local git?

```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <useLastCommittedRevision>true</useLastCommittedRevision>
                </configuration>
            </plugin>
````

**Comment by ram4git** [comment]
did you find the solution?

**Comment by bmarwell** [comment]
Hi @hrzafer, is this snipped from the repository root? I think the scm dependency had a bug.

**Comment by infini667** [comment]
I'm getting this error... Can I use an older version? How can I find the plugin versions?

**Comment by infini667** [comment]
Apparently this plugin works with local git. At least is not building if you have git changes not commited, doCheck true and you are using that git build number as your buildNumber. However, it will not work for some reason if you do not specify the SCM, but you don't need to specify a correct one.

```
<project>
    <scm>
        <connection>anything</connection>
        <developerConnection>anything</developerConnection>
        <url>anything</url>
    </scm>
</project>
```
