### ISSUE TITLE
Local modifications are ignored if module not at git repo root level

### ISSUE THREAD

**Issue by suniala** [mojohaus/buildnumber-maven-plugin#14]
I have a project using buildnumber-maven-plugin with a git repo. The problem is that doCheck=true does not result in a build failure when local modifications exist. After some searching and hacking I came to the conclusion that this is a bug.

I created a test project with similar setup but could not reproduce the problem at first. Then I moved the Maven module from the root level of the repo under a sub directory. This setup does reproduce the problem and matches the layout of my actual project.

See my test project at https://github.com/suniala/buildnumber-test. The first version, where doCheck=true works as expected, is available at master. The branch module-not-at-root-level contains the failing version.

Note that I am aware of #5 and noticed that removing the format did not affect the outcome with my test project.

**Comment by veselov** [comment]
I'm seeing the same problem. I don't understand how it's not failing considering the source...
```
[DEBUG] org.codehaus.mojo.build.CreateMojo - Verifying there are no local modifications ...
[INFO] org.apache.maven.scm.manager.plexus.DefaultScmManager - Executing: /bin/sh -c cd /home/vps/ws/Trunomi/mobile_backend/mock_server/tru-api/api-core && git rev-parse --show-toplevel
[INFO] org.apache.maven.scm.manager.plexus.DefaultScmManager - Working directory: /home/vps/ws/Trunomi/mobile_backend/mock_server/tru-api/api-core
[INFO] org.apache.maven.scm.manager.plexus.DefaultScmManager - Executing: /bin/sh -c cd /home/vps/ws/Trunomi/mobile_backend/mock_server/tru-api/api-core && git status --porcelain .
[INFO] org.apache.maven.scm.manager.plexus.DefaultScmManager - Working directory: /home/vps/ws/Trunomi/mobile_backend/mock_server/tru-api/api-core
[DEBUG] org.apache.maven.scm.manager.plexus.DefaultScmManager -  M mock_server/tru-api/api-core/pom.xml
[DEBUG] org.codehaus.mojo.build.CreateMojo - Updating project files from SCM: skipped.
```
