### ISSUE TITLE
Use project.build.outputTimestamp when available ?

### ISSUE THREAD

**Issue by jonenst** [mojohaus/buildnumber-maven-plugin#168]
For projects wanting reproducible builds (they have set project.build.outputTimestamp ), maybe this plugin could use the value for the "timestamp" ? This means less migrations for projects using the timestamp property from this plugin and wanting to become reproducibl. Also it allows to use the same code to build reproducible and non reproducible builds, by just defining the project.build.outputTimestamp  property. I don't think that there exists something in maven to make it easy to have a property that has either the project.build.outputTimestamp  or now()

**Comment by splatch** [comment]
I think it is relevant suggestion. Other way could be build number plugin populating `project.build.outputTimestamp` with scm date.

**Comment by splatch** [comment]
Looks like #16 brings some support for reading last change from scm.
