### ISSUE TITLE
Support for flagging a property if local changes are present

### ISSUE THREAD

**Issue by veselov** [mojohaus/buildnumber-maven-plugin#17]
I see there is a way to fail the plugin in presence of local changes. This is good, as it would taint the version number, but is not particularly development friendly. I either have to set doCheck to true, and developers won't be able to build until they somehow override it, or not set doCheck, and risk somebody publishing a build that has local changes in it.

It would be great if BuildNumber could set another project property that would indicate whether the build is tainted or not, so then it can be published the same way as others into the project artifacts, so it can be clearly seen whether the binary was built from a clean clone or not.

**Comment by jan-tosovsky-cz** [comment]
+1 exactly this I am missing a lot!
