### ISSUE TITLE
scmBranch on SVN does not work properly when plugin is run by submodule

### ISSUE THREAD

**Issue by pwielgolaski** [mojohaus/buildnumber-maven-plugin#27]
When SVN info reports URL, it reports also subfolder like
http://svn/project/branches/3.4/submodule
scmBranch should be branches/3.4, but it is branches/3.4/submodule

Simple fix would be to replaces pattern from here https://github.com/mojohaus/buildnumber-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/build/CreateMojo.java#L650 
with 
scmUrl.replaceFirst(".*((branches|tags)/[^/]*).*", "$1" );

**Comment by johnsonlee** [comment]
What's the latest version for this issue fix?
