### ISSUE TITLE
Builld fails if -Dmaven.buildNumber.doUpdate=true - tries to update from `master` instead of current branch?

### ISSUE THREAD

**Issue by d4nirod** [mojohaus/buildnumber-maven-plugin#35]
So current branch is `feature-branch`. `doCheck` goes OK but `doUpdate` doesn't as it seems to try it on `master` instead of the actual current branch for no apparent reason.

[d4nirod@mac-mini:cw-server (feature-branch)]$ mvn -Dmaven.buildNumber.doCheck=true -Dmaven.buildNumber.doUpdate=true install
[INFO] Scanning for projects...  
[INFO] ------------------------------------------------------------------------
[INFO] Building Ckrs 1.0
[INFO] ------------------------------------------------------------------------
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ cw-server ---
[INFO] Executing: /bin/sh -c cd '/Users/d4nirod/Documents/workspace/cw-server' && 'git' 'rev-parse' '--show-toplevel'
[INFO] Working directory: /Users/d4nirod/Documents/workspace/cw-server
[INFO] Executing: /bin/sh -c cd '/Users/d4nirod/Documents/workspace/cw-server' && 'git' 'status' '--porcelain' '.'
**[INFO] Executing: /bin/sh -c cd '/Users/d4nirod/workspace/cw-server' && 'git' 'log' '-n1' '--date-order' 'master'**
[INFO] Working directory: /Users/d4nirod/workspace/cw-server
[ERROR] Provider message:
[ERROR] The git-log command failed.
[ERROR] Command output:
[ERROR] fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.992 s
[INFO] Finished at: 2016-04-12T09:34:02+02:00
[INFO] Final Memory: 12M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project cw-server: Couldn't update project. Error! -> [Help 1]
[ERROR]

**Comment by VictorBHub** [comment]
same issue here..

**Comment by Sherpard** [comment]
Having the same issue here :|

**Comment by j256** [comment]
I fixed this by setting the `doUpdate` in `configuration` to `false`.  We are using CI anyway so we don't need to update the code.  YMMV.

 				<configuration>
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>  <-----  changed this from true
				</configuration>
