### ISSUE TITLE
scm parameters are ignored during ${buildNumber} value is set

### ISSUE THREAD

**Issue by onurbaysan** [mojohaus/buildnumber-maven-plugin#36]
Although I set scm url as https://xxx/svn/yyy/trunk/zzz/ttt/aaa/bbb, it always set to the last commit number of https://xxx/svn/yyy/trunk. It ignores the part after trunk.

I changes scm url to another svn like https://aaa/svn/trunk, like previous example, ${buildNumber} is set to https://xxx/svn/yyy/trunk

I don't know whether it is a bug or not. If it is not, is there a way to get revision number of a specific folder in svn?

**Comment by khmarbaise** [comment]
Can you show a full example (best is having a full working example project) which shows the behaviour?

**Comment by onurbaysan** [comment]
About April 25, I tried buildnumber locally. I've searched for sample usage but  and I've never committed the usage of it. Sorry for this.

After getting wrong revision numbers, I change it to use manifest entries specified in properties on maven-jar-plugin.

Finally we started to use Jenkins environment variables as svn revision of the project. 

Thank you for your response.
