### ISSUE TITLE
Properties mentioned in documentation are just wrong.

### ISSUE THREAD

**Issue by merzedes** [mojohaus/buildnumber-maven-plugin#37]
http://www.mojohaus.org/buildnumber-maven-plugin/create-mojo.html
> Build numbers are not automatically reflected in your artifact's filename, but can be added to the metadata. You can access the build number in your pom with ${buildNumber}. You can also access ${timestamp} and the SCM branch of the build (if applicable) in ${SCMBranch}

1. buildNumber => build.revision
2. SCMBranch  => scmBranch

This list is very likely not complete.

**Comment by khmarbaise** [comment]
The property `${buildNumber}` is correct and not `build.revision`.
What you have identified correct is that the description text which mentions `${SCMBranch}`  is wrong. This must be corretly `${scmBranch}` instead.

**Comment by renfeng** [comment]
The document still mentions the wrong ${SCMBranch}.

Besides, it cannot be renamed with scmBranchPropertyName, e.g. 		```<scmBranchPropertyName>buildScmBranch</scmBranchPropertyName>```
