### ISSUE TITLE
Buildnumber plugin does not fail on doCheck if format is specified

### ISSUE THREAD

**Issue by rlaun** [mojohaus/buildnumber-maven-plugin#5]
In the create mojo, the doCheck option is not honored if format is configured.
This can be verified by adding this to the plugin configuration in the integration test MBUILDNUM-85:

``` xml
  <format>{0,date,yyyyMMdd}-{1}</format>
  <items>
    <item>timestamp</item>
    <item>scmVersion</item>
  </items>
```

**Comment by rlaun** [comment]
The proposed fix seems too trivial... not sure why the check was only in the _else_ branch.

**Comment by arcasys** [comment]
This issue has been resolved in 
https://github.com/arcasys/buildnumber-maven-plugin
Also, doCheck, and getRevisionsOnlyOnce will work with format.
Feel free to merge this change and let me know when you've done so, so I can delete my fork.

Thanks, Hans
