### ISSUE TITLE
With Git SCM allow staged changes in working copy

### ISSUE THREAD

**Issue by jgeorgeson** [mojohaus/buildnumber-maven-plugin#52]
I'm currently setting up to fail on dirty working copy. However developers are somewhat frustrated with the change and try find ways to globally disable it in their workspace. To encourage them to not disable the check, I'd like to see configuration to allow staged changes. That way their work is at least marked for commit, but they don't have to worry about amending/rebasing a commit they made just to avoid the Maven failure due to local modifications.

**Comment by sjoerdtalsma** [comment]
This is probably related to #21 in some way.
