### ISSUE TITLE
${scmBranch} is returning UNKNOW

### ISSUE THREAD

**Issue by vendeza** [mojohaus/buildnumber-maven-plugin#53]
I'm using mercruial and buildnumber-maven-plugin 1.4. And command ${scmBranch} return value UNKNOW. What i need to do to get branch name information from buildnumber-maven-plugin?
My pom.xml:
```
<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-war-plugin</artifactId>
          <version>2.6</version>
          <configuration>
            <archive>
              <manifest>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              </manifest>
              <manifestEntries>
                <Implementation-Build>${buildNumber}</Implementation-Build>
                <SCM-Build>${scmBranch}</SCM-Build>
              </manifestEntries>
            </archive>
          </configuration>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>buildnumber-maven-plugin</artifactId>
        <version>1.4</version>
        <executions>
          <execution>
            <phase>validate</phase>
            <goals>
              <goal>create</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <doCheck>false</doCheck>
          <doUpdate>false</doUpdate>
          <scmBranchPropertyName>true</scmBranchPropertyName>


        </configuration>
      </plugin>
```

**Comment by RockyMM** [comment]
Duplicate of #9

**Comment by dusuney** [comment]
Ok. I resolved it. I added "maven-antrun-plugin".
Next set helped me:
`<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <warSourceDirectory>src/main/webapp</warSourceDirectory>
                    <warName>${project.finalName}</warName>
                    <archive>
                       <manifest>
                        <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                        <manifestEntries>
                            <SCM-Product>КПИ.АПЦ.ЗК</SCM-Product>
                            <SCM-Branch>${scmBranch}</SCM-Branch>
                            <SCM-Revision>${changeSet}</SCM-Revision>
                            <SCM-Date> ${timestamp} </SCM-Date>
                        </manifestEntries>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>manifest</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-antrun-plugin</artifactId>
              <version>1.8</version>
              <executions>
               <execution>
                <phase>validate</phase>
                <goals>
                 <goal>run</goal>
                </goals>
                <configuration>
                 <exportAntProperties>true</exportAntProperties>
                 <target>
                  <exec executable="hg" outputProperty="scmBranch">
                      <arg value="id"/>
                      <arg value="-b"/>
                  </exec>
                 </target>
                </configuration>
               </execution>
              </executions>
             </plugin>
//...
<plugins>`

**Comment by RockyMM** [comment]
@dusuney cool solution, but just workaround. It seems possible to solve. Let's continue the discussion ni #9

**Comment by alevinetx** [comment]
I'm having this same issue with git, ${scmBranch} is null in later phases after running create   Is there a similar work around?

**Comment by alevinetx** [comment]
I did find a work around, actually.   I'm running create-metadata twice.  First time in the initialize phase, which as a result puts my variable in the environment.  The 2nd time in generate-resources phase, and my variable is available for the [properties/] section.
So:

    validate:   create
    initialize:  create-metadata
    generate-resources:  create-metadata
    

Hopefully this helps anyone else who has this issue.   This plugin was helpful in debugging what was present and when:   			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.6</version>
				<executions>
					<execution>
						<phase>initialize</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<property environment="env" />
								<echoproperties />
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>


Cheers!

**Comment by alevinetx** [comment]
My solution may have been premature.   It works great on my local machine, but returns UNKNOWN when run on a node, launched from Jenkins.  Same files, same goals.     Any guidance would be greatly appreciated.

Local Machine:
    Eclipse NEON
    SourceTree - embedded git 2.8.1
    Eclipse embedded maven:   3.3.9

Jenkins machine:
   Jenkins 1.630
   git plugin: 2.4.0

Node:   
  git  1.8.3.1
  maven 3.3.9 (pushed from Jenkins)
  RHEL 7.3 (3.10.0-514.el7)

**Comment by Jorelia** [comment]
Still getting unknown....on June 27, 2017....cannot get the branch.... when do you plan to fix it ?

**Comment by raja-anbazhagan** [comment]
@Jorelia If you are using Jenkins or some automated CI tool, Its most likely that the commit was checked out in a detached state. In detached state, HEAD won't have the branch information

**Comment by markkolich** [comment]
> If you are using Jenkins or some automated CI tool, Its most likely that the commit was checked out in a detached state. In detached state, HEAD won't have the branch information

This was exactly my problem &mdash; I'm using AWS CodeBuild in my CI pipeline which shallow clones the repository under build, hence no branch information is available to the `buildnumber-maven-plugin`. I assume most Jenkins builds would have the same problem, unless you're full/deep cloning the repo under build?

In my case, the fix was to set the `buildScmBranch` and `buildNumber` system properties to match those values provided by my CI pipeline, instead of relying on the `buildnumber-maven-plugin` to extract these values via `git`:

```
mvn -DbuildScmBranch=${CODEBUILD_GIT_BRANCH} -DbuildNumber=${CODEBUILD_GIT_COMMIT_SHORT} \
  clean package
```

`${CODEBUILD_GIT_BRANCH}` and `${CODEBUILD_GIT_COMMIT_SHORT}` are environment variables set by my CI pipeline.

**Comment by stanarnold** [comment]
Had a similar issue. My problem was that the sample code I had for configuring the build number plugin was dead wrong. Looks like we were testing with the same bad config.

`<scmBranchPropertyName>true</scmBranchPropertyName>` is the problem...

Here is my working configuration if anyone else (new to this plugin) runs into this issue:

```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <doCheck>false</doCheck>
                    <doUpdate>false</doUpdate>
                    <scmBranchPropertyName>scmBranch</scmBranchPropertyName>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
                    <archive>
                        <manifestEntries>
                            <Build-Time>${maven.build.timestamp}</Build-Time>
                        </manifestEntries>
                        <manifestSections>
                            <manifestSection>
                                <name>Versions</name>
                                <manifestEntries>
                                    <Implementation-Version>${project.version}</Implementation-Version>
                                    <Implementation-SCM-Revision>${buildNumber}</Implementation-SCM-Revision>
                                    <Implementation-SCM-Branch>${scmBranch}</Implementation-SCM-Branch>
                                </manifestEntries>
                            </manifestSection>
                        </manifestSections>
                    </archive>
                </configuration>
            </plugin>
```

Hope this helps someone else.
