### ISSUE TITLE
Don't need SCM, only want to use local file (was possible in 1.0-beta-3)

### ISSUE THREAD

**Issue by drswaki69** [mojohaus/buildnumber-maven-plugin#54]
I would like still the use the local file (default buildNumber.properties).
Would like to have an option in the configuration that skips the SCM functionality and uses the local file.
This was the default behavior in 1.0-beta-1, 1.0-beta-2, 1.0-beta-3.

Reason: the one that builds the app using maven should not always have access to the SCM, but still wants to see which build attempt he is looking at.

**Comment by khmarbaise** [comment]
Can you explain your idea/backward idea? What is the exact purpose of that?

**Comment by drswaki69** [comment]
There are a couple of situations when you don't want to have access the version control repository, when you are building, but would like to see which build number / attempt it is.

The current version does not support that. When there is a SCM node in the POM the current version will try to fetch the build number from the repository. 

It should be an option if you would like to fetch build number from source controle or not.
The option to use the local file to just see your local build attempt is what you need at some situations

**Comment by khmarbaise** [comment]
maybe I misunderstand a thing here...but if you are working locally for example with SVN, Git etc. the version can be extracted so I don't see the point here?  Apart from that why not offering a patch implements the wished behaviour?
