### ISSUE TITLE
Maven fails to parse the plugin on version 1.4

### ISSUE THREAD

**Issue by drewed** [mojohaus/buildnumber-maven-plugin#56]
I've been struggling to get the buildnumber plugin working in my maven project.  At first, maven wouldn't download it from the maven2 repository.  Then it somehow got scrambled (sha1 sum did not match).  I manually downloaded it an placed it and the checksum in my .m2 folder under the appropriate path.  However, maven still complains about the plugin saying it doesn't have a pom and the plugin descriptor is bad (see below clean build output).  Any help would be appreciated.

I'm building on a mac 10.11.6 (El Capitan).

> $ mvn clean install
> [INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Project 0.1
> [INFO] ------------------------------------------------------------------------
> [WARNING] The POM for org.codehause.mojo:buildnumber-maven-plugin:jar:1.4 is missing, no dependency information available
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 0.161 s
> [INFO] Finished at: 2017-01-09T08:34:41-07:00
> [INFO] Final Memory: 8M/309M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to parse plugin descriptor for org.codehause.mojo:buildnumber-maven-plugin:1.4 (/Users/drewed/.m2/repository/org/codehause/mojo/buildnumber-maven-plugin/1.4/buildnumber-maven-plugin-1.4.jar): error in opening zip file -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginDescriptorParsingException

**Comment by khmarbaise** [comment]
The problem is simply that your groupId: `org.codehause.mojo`  is simply wrong cause it is `org.codehaus.mojo`...

**Comment by drewed** [comment]
@khmarbaise Thank you!  Sometimes one needs a second pair of eyes.  Sigh.

**Comment by khmarbaise** [comment]
You're welcome.

**Comment by Floryndas** [comment]
Dear,
I have got the same error, but looking to my groupId, it seems to be already correct. Do you have any idea of the problem, please? Below is the pom.xml content:


* <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <format>{0,number}</format>
                    <items>
                        <item>buildNumber0</item>
                    </items>
                </configuration>
            </plugin> *
Here is the error I have when executing mvn install:
 
*Failed to parse plugin descriptor for org.codehaus.mojo:buildnumber-maven-plugin:1.4 (C:\Users\Justine\.m2\repository\org\codehaus\mojo\buildnumber-maven-plugin\1.4\buildnumber-maven-plugin-1.4.jar): error in opening zip file -> [Help 1]*
