### ISSUE TITLE
Add support for Last Changed Date

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [mojohaus/buildnumber-maven-plugin#60]
It would be nice to support the 'last changed date' property as well. Currently only build date is available, which is suboptimal in certain scenarios. It is covered in the following (old) pull request: https://github.com/mojohaus/buildnumber-maven-plugin/pull/16/commits/8c0f41458e55e2fe3e3e9644437f7e1c832346e9

Would it be possible to review it and integrate?

**Comment by khmarbaise** [comment]
Unfortunately this PR does not contain a single test...

**Comment by jan-tosovsky-cz** [comment]
I am quite lost in test folders. Is there any example how such a test should look like? Btw, in this case the manifest content is generated when tests are already finished so it is hard to check the result in advance. But I am most likely missing something.

**Comment by sudr** [comment]
I was looking for a way to not only get the git commit hash but also the time of the commit. I'm not sure if this concept of LastChangedDate is what I would need. If so, I'd be happy to take this work on to get it ready for consideration for a merge.
