### ISSUE TITLE
Including the locale revision number for the goal hgchangeset

### ISSUE THREAD

**Issue by preafos** [mojohaus/buildnumber-maven-plugin#63]
Hallo,
thank you for providing this nice maven plugin. I just wondered, if you could also add support for the locale revision number in mercurial? It's usually query with "hg id -n" and is an integer value, i. e. "100" or "100+". It would be great, if you could add support for this minor feature of mercurial.

I already modified the existing HgChangeSetMojo.java file and attached it to this post. So it's more or less a simple switch.
[HgChangeSetMojo.txt](https://github.com/mojohaus/buildnumber-maven-plugin/files/1053454/HgChangeSetMojo.txt)

**Comment by khmarbaise** [comment]
If you already made the changes than it would be better to do a pull request here on Github...so I can take a look on it and if it fits I can merge your change into the plugin...

**Comment by preafos** [comment]
I haven't actually haven't pulled the code nor have I done a pull request on github. ... In short I don't know the procedure.

**Comment by preafos** [comment]
#64 has been created.

**Comment by olegshtch** [comment]
I cleaned up PR #64 in #73.
