### ISSUE TITLE
Fails to find "https" provider !?

### ISSUE THREAD

**Issue by tombensve** [mojohaus/buildnumber-maven-plugin#67]
With the web page example config:

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <doCheck>true</doCheck>
                    <doUpdate>true</doUpdate>
                </configuration>
            </plugin>

I get:

    [ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project aps-vertx-provider: Cannot get the revision information from the scm repository :
    [ERROR] No such provider: 'https'.

Note that my git repo does not use https as protocol! It is git@...

**Comment by khmarbaise** [comment]
Can you please make a full test project...

**Comment by tombensve** [comment]
So far, for all maven plugins I’ve used, just copying the documented example and possibly modifying parts have worked fine. For this one it didn’t.

This issue was just for your information. You do what you want with it. I have already moved on to find another, simpler solution since I unfortunately don’t have the time.

Best Regards,
Tommy


Från: Karl Heinz Marbaise <notifications@github.com>
Svara: mojohaus/buildnumber-maven-plugin <reply@reply.github.com>
Datum: 5 augusti 2017 at 13:13:00
Till: mojohaus/buildnumber-maven-plugin <buildnumber-maven-plugin@noreply.github.com>
Cc: Tommy Svensson <tommy@natusoft.se>, Author <author@noreply.github.com>
Ämne:  Re: [mojohaus/buildnumber-maven-plugin] Fails to find "https" provider !? (#67)  

Can you please make a full test project...
