### ISSUE TITLE
Revision found on update is overwritten

### ISSUE THREAD

**Issue by kkoster** [mojohaus/buildnumber-maven-plugin#70]
I am trying to use the buildnumber-maven-plugin (v1.4) with a Perforce repository. I am getting the following logged messages:

>[INFO] Got a revision during update: 4079887 
>[INFO] Storing buildNumber: null at timestamp: 1506951375881

The CreateMojo.update() methodis discovering the correct revision number (1st log message). However, after it is found an unconditional call to getRevision() is made that wipes it out because it calls the info() method on the repository provider (which the perforce provider does not implement and simply returns null). Once the revision is discovered (on update()), why not just return it?

**Comment by johnmanko** [comment]
Should this be closed?

**Comment by khmarbaise** [comment]
No cause the code has not yet integrated...

**Comment by johnmanko** [comment]
As long as this project isn't dead. It's a very important plugin, imo. :)  Thanks for the work on it!
