### ISSUE TITLE
Support git-svn

### ISSUE THREAD

**Issue by albfan** [mojohaus/buildnumber-maven-plugin#72]
For old projects based on svn would be great to support git-svn:

The use case is:

1. pom scm section is set to a svn url
2. provider is set as javasvn
3. repo is a git-svn clone
4. Want to extract the revision number from checkout
```
commit 10a3ae3fc8d83532266ee1ff58694cd569935aa3 (HEAD, origin/trunk)

Author: Alberto <alberto@email.com>
Date: Wed Mar 7 16:11:01 2018 +0000

commit message

git-svn-id: http://svn.com@8715 2d76ea88-ba9a-4675-b1a1-0fb15de6bd4c
```

So here the `scmVersion` would be 8715

Now the result is:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.882 s
[INFO] Finished at: 2018-03-08T12:50:52+01:00
[INFO] Final Memory: 18M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project myProject: Cannot get the revision information from the scm repository :
[ERROR] Exception while executing SCM command. svn: E155007: 'C:\myProject' is not a working copy
```

I understand the problem could be solved on scm provider, so I open too https://issues.apache.org/jira/browse/SCM-872

**Comment by albfan** [comment]
Just an option to avoid failure if a working copy is not detected would be great

**Comment by khmarbaise** [comment]
Do you have something like this http://www.mojohaus.org/buildnumber-maven-plugin/create-mojo.html#revisionOnScmFailure in mind?

**Comment by albfan** [comment]
hmm, that almost fix it for me. I don't want to touch pom.xml definition so once I'm on correct commit:

    $ mvn clean package -Dmaven.buildNumber.revisionOnScmFailure=$(git log -n1 | grep git-svn-id | cut -d@ -f2 | cut -d" " -f1)

Fixed it.

Next doubts: Can I force to use another scm implementation provider from command line? I could implement a git-svn provider that do the same as my hacky oneliner but need to override from command line.

**Comment by albfan** [comment]
I see there's no user property for providerImplementations. Something like:

    maven,buildNumber.providerImplementations="svn=foo,git=bar"

could work, Then foo provider will retrieve revision from log commit. Anyway if I need to add a parameter that oneliner could be enough. If this go nowhere please close the issue. I mean Do you think about support revision numbers from bridged repos like git-svn?

**Comment by khmarbaise** [comment]
Maybe I'm wrong but it looks you are going to complicated why not adding the `revisionOnScmFailure` enty in your pom with a hard coded value which shows things like `UNKNOWN` and using the scm entry to extract the git sha1 ...this can be done automatically..also in SVN ...Apart from that have you taken a look in on the usage page: http://www.mojohaus.org/buildnumber-maven-plugin/usage.html there is an example for the provider implementation..furthermore I would suggest to go for SVN provider cause the code is done in SVN instead of git...

**Comment by albfan** [comment]
Let me explain: The project is under subversion, the pom is correct as it is. Normally project is built under jenkins so everything works fine (buildNumber is retrieved correctly from a svn checkout).

Now I have a local setup where I use the project under git-svn, so my repo is a git one. That's why I have the error (this is not a svn working copy). Your suggestion for `revisionOnScmFailure` already fixed my problem, but as git-svn is there to stay, maybe it is possible to support it.

Make a svn provider understand git sounds weird (although is the best approach for me) that's why I think in a solution at buildnumber-plugin level, whether allowing to override svn scm provider or detecting a scm config under a git-svn repo (I think buildnumber-plugin knows nothing about scm and delegates on configured provider so first one option is the only I think could work).

I'm on linux, but as command line programs may vary from system to system, and maven is multiplatform extract revision number from a maven scm provider seems safety.

I will try to provide a PR for this: Support override providerImplementations from command line like:

    maven.buildNumber.providerImplementations.svn=foo

and will implement a git-svn provider doing same parsing in my oneliner command

As said, Is totally understandable this is a no-go and you decide to close it
