### ISSUE TITLE
Cannot create the build number because you have local modifications : ...

### ISSUE THREAD

**Issue by dingxiaobo** [mojohaus/buildnumber-maven-plugin#81]
Using this plugin, I can't test my changed code before I commit those changes.
Are there any configuration property to disable this check ? I can't find one in [doc](https://www.mojohaus.org/buildnumber-maven-plugin/create-mojo.html).  

![image](https://user-images.githubusercontent.com/23743074/45006267-9cc3e900-b02a-11e8-99d3-0bc01ce953d4.png)

**Comment by kkolinko** [comment]
`-Dmaven.buildNumber.doCheck=false`  or `<doCheck>false</doCheck>`?

This property is mentioned in the [usage guide](https://www.mojohaus.org/buildnumber-maven-plugin/usage.html) as well as in the [reference doc](https://www.mojohaus.org/buildnumber-maven-plugin/create-mojo.html#doCheck) that you have linked to.
