### ISSUE TITLE
`scmBranch` property not set on mercurial repo

### ISSUE THREAD

**Issue by tbrugz** [mojohaus/buildnumber-maven-plugin#9]
`scmBranch` property is not set when using a mercurial repo. The `hgchangeset` goal also does not set a `branch` property.

**Comment by tbrugz** [comment]
I have working code for a fix, will send a pull request

**Comment by hiro2k** [comment]
Came to report this, but the proposed pull request looks correct. Can you merge it in?

**Comment by RockyMM** [comment]
Hey, I took a quick glance at @tbrugz PR, and it looks OK. Cannot test it myself, but I would love to have it in buildnumber plugin, as my team is a recent HG user.

**Comment by dusuney** [comment]
Try add it:
`<plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-antrun-plugin</artifactId>
              <version>1.8</version>
              <executions>
               <execution>
                <phase>validate</phase>
                <goals>
                 <goal>run</goal>
                </goals>
                <configuration>
                 <exportAntProperties>true</exportAntProperties>
                 <target>
                  <exec executable="hg" outputProperty="scmBranch">
                      <arg value="id"/>
                      <arg value="-b"/>
                  </exec>
                 </target>
                </configuration>
               </execution>
              </executions>
             </plugin>`

**Comment by khmarbaise** [comment]
Can someone make a pull request from it so i could integrate it into buildnumber-maven-plugin?

**Comment by gallaman** [comment]
This appears to still be a problem in 1.4. Tried dusuney's workaround, no joy. It occurs to me that the build number without the branch is pretty useless unless there is a convention that builds are always done only on the trunk.
