### ISSUE TITLE
SVN passwords leaked into maven log

### ISSUE THREAD

**Issue by llech** [mojohaus/buildnumber-maven-plugin#96]
The SVN passwords are leaked into the log in version 1.4.

My plugin configuration:

  <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>buildnumber-maven-plugin</artifactId>
    <executions>
      <execution>
        <phase>validate</phase>
        <goals>
          <goal>create</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <doCheck>false</doCheck>
      <doUpdate>true</doUpdate>
    </configuration>
  </plugin>

The log content:

[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ project ---
[INFO] Executing: /bin/sh -c cd '/home/build/tmp/project' && 'svn' '--username' 'svn-user' '--password''*****' '<svn-pass-plaintext>' '--no-auth-cache' '--non-interactive' 'update' '/home/build/tmp/project'

Runtime environment: JRE 1.8, Ubuntu 18.04, script run inside docker image. Maven flags: -B (batch-mode). 

The bug was introduced in 1.4, downgrading to 1.3 has solved the issue.

**Comment by gerevesi** [comment]
This also happens to me when using version 1.4, although it only happens to some of our team members.
While analyzing the differences, we noticed that this only happens when the password has been set in maven's settings.xml file.
In my case, the password is NOT in plaintext (I'm using password encryption as described [here](https://maven.apache.org/guides/mini/guide-encryption.html))

**Comment by llech** [comment]
I've changed to even better solution, not using that plugin at all.

Apparently the developers doesn't care about security. How many other bugs you introduce to your build pipeline by using such a plugin that provides actually no important functionality?

**Comment by bmarwell** [comment]
Hi @llech,
thanks for bringing this to our attention.
They main communication is the mailing list, but you're also welcome to create a PR yourself.

In contrast to Apache software, the mojohaus software is not being maintained under the oversight of a foundation, but most developers are also Apache committers.

I'll see what can be done here, though.

Best regards,
Ben

**Comment by bmarwell** [comment]
@llech @gerevesi I found this commit:
https://github.com/apache/maven-scm/commit/60d98849047f11daec78e2fb14938c12776e68c3

Maybe this plugin just needs an update.

**Comment by bmarwell** [comment]
@llech  please try the current 3.0.0-SNAPSHOT revision which @dantran has released.
